version: "3"
services:
  node:
    build: ./
    container_name: storkfe
    user: "node"
    working_dir: /app
    environment:
      - NODE_ENV=development
      - STORK_FE_PORT
    volumes:
      - "./:/app"